Added Beginning Support for Debian/Ubuntu installs

diff --git a/base/aac-base.install b/base/aac-base.install
--- a/base/aac-base.install
+++ b/base/aac-base.install
@@ -9,7 +9,7 @@
 # Target: CentOS/RHEL 7
 #
 ###
-VERSION="1.6.4"
+VERSION="1.7.0"
 
 function version() {
 	echo "$0 version is $VERSION"
@@ -21,6 +21,75 @@ function version() {
 		echo -n "$y version "
 		eval ${y}_version
 	done
+}
+
+function findos() {
+	if [ -e /etc/os-release ]
+	then
+		. /etc/os-release
+		theos=`echo $ID | tr [:upper:] [:lower:]`
+	elif [ -e /etc/centos-release ]
+	then
+		theos=`cut -d' ' -f1 < /etc/centos-release | tr [:upper:] [:lower:]`
+		VERSION_ID=`awk '{print $3}' /etc/centos-release | awk -F. '{print $1}'`
+	elif [ -e /etc/redhat-release ]
+	then
+		theos=`cut -d' ' -f1 < /etc/redhat-release | tr [:upper:] [:lower:]`
+		VERSION_ID=`awk '{print $3}' /etc/redhat-release | awk -F. '{print $1}'`
+	elif [ -e /etc/fedora-release ]
+	then
+		theos=`cut -d' ' -f1 < /etc/fedora-release | tr [:upper:] [:lower:]`
+		VERSION_ID=`awk '{print $3}' /etc/fedora-release | awk -F. '{print $1}'`
+	elif [ -e /etc/debian-release ]
+	then
+		theos=`cut -d' ' -f1 < /etc/debian-release | tr [:upper:] [:lower:]`
+		VERSION_ID=`awk '{print $3}' /etc/debian-release | awk -F. '{print $1}'`
+	else
+		colorecho "Do not know this operating system. LinuxVSM may not work." 1
+		theos="unknown"
+	fi
+	export VERSION_ID
+}
+
+function checkdep() {
+	dep=$1
+	needdep=0
+	if [ Z"$theos" = Z"centos" ] || [ Z"$theos" = Z"redhat" ] || [ Z"$theos" = Z"fedora" ]
+	then
+		rpm -q $dep >& /dev/null
+		if [ $? -ne 0 ]
+		then
+			echo "Missing Dependency $dep"
+			needdep=1
+		fi
+	elif [ Z"$theos" = Z"debian" ] || [ Z"$theos" = Z"ubuntu" ]
+	then
+		dpkg -s $dep >& /dev/null
+		if [ $? -ne 0 ]
+		then
+			echo "Missing Dependency $dep"
+			needdep=1
+		fi
+	elif [ Z"$theos" = Z"unknown" ]
+	then
+		echo "Cannot Check Dependenty $dep"
+	fi
+}
+
+function installdep() {
+	if [ Z"$theos" = Z"centos" ] || [ Z"$theos" = Z"redhat" ] || [ Z"$theos" = Z"fedora" ]
+	then
+		yum -y install $INSTALL $DEVEL
+	elif [ Z"$theos" = Z"debian" ] || [ Z"$theos" = Z"ubuntu" ]
+	then
+		which apt-get >& /dev/null
+		if [ $? -eq 0 ]
+		then
+			apt-get install -y $DINSTALL $DDEVEL
+		else
+			apt install -y $DINSTALL $DDEVEL
+		fi
+	fi
 }
 
 function menu() {
@@ -58,21 +127,25 @@ function startsrv() {
 
 function tz() {
 	echo "Checking Timezone settings"
-	yum -q makecache fast
-	echo $RPMLIST | grep ntp- > /dev/null
-	if [ $? != 0 ]
+	if [ -e /usr/bin/yum ]
+	then
+		yum -q makecache fast
+	fi
+	checkdep ntp
+	if [ $needdep -eq 1 ]
 	then
 		echo "Install/update ntp"
-		yum -q makecache fast
-		yum -q -y install ntp
-		yum -q -y update ntp
+		INSTALL=ntp
+		DINSTALL=$INSTALL
+		installdep
 	fi
-	echo $RPMLIST | grep wget > /dev/null
-	if [ $? != 0 ]
+	checkdep wget
+	if [ $needdep -eq 1 ]
 	then
 		echo "Install/update wget"
-		yum -q -y install wget
-		yum -q -y update wget
+		INSTALL=wget
+		DINSTALL=$INSTALL
+		installdep
 	fi
 	settz=0
 	ls -al /etc/localtime |grep "$TZ" > /dev/null
@@ -98,12 +171,15 @@ function tz() {
 
 function epel() {
 	echo "Checking for EPEL repository"
-	echo $RPMLIST |grep epel-release-${VERSION_ID} > /dev/null
-	if [ $? != 0 ]
+	checkdep epel-release
+	if [ $needdep -eq 1 ]
 	then
-		echo "Installing EPEL repository"
-		wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-${VERSION_ID}.noarch.rpm
-		rpm -ivh epel-release-latest-${VERSION_ID}.noarch.rpm
+		if [ Z"$theos" = Z"centos" ] || [ Z"$theos" = Z"redhat" ] || [ Z"$theos" = Z"fedora" ]
+		then
+			echo "Installing EPEL repository"
+			wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-${VERSION_ID}.noarch.rpm
+			rpm -ivh epel-release-latest-${VERSION_ID}.noarch.rpm
+		fi
 	fi
 }
 
@@ -111,13 +187,25 @@ function selinux() {
 	#
 	# only install if needed
 	echo "Checking for SELinux Policy RPMS"
-	echo $RPMLIST | grep policycoreutils-python > /dev/null
-	if [ $? != 0 ]
+	if [ Z"$theos" = Z"centos" ] || [ Z"$theos" = Z"redhat" ] || [ Z"$theos" = Z"fedora" ]
 	then
-		echo "Installing SELinux Policy RPMS"
-		yum -q -y install policycoreutils-python setroubleshoot-server
-		yum -q -y update policycoreutils-python setroubleshoot-server
+		checkdep policycoreutils-python
+		if [ $needdep -eq 1 ]
+		then
+			echo "Installing SELinux Policy RPMS"
+			INSTALL="policycoreutils-python setroubleshoot-server"
+			DINSTALL=$INSTALL
+		fi
+	elif [ Z"$theos" = Z"debian" ] || [ Z"$theos" = Z"ubuntu" ]
+	then
+		checkdep policycoreutils
+		if [ $needdep -eq 1 ]
+		then
+			INSTALL="policycoreutils selinux-utils"
+			DINSTALL=$INSTALL
+		fi
 	fi
+	installdep
 	echo "If SELinux issues pop up use the following to debug:"
 	echo "	sealert -a /var/log/audit/audit.log"
 }
@@ -148,11 +236,18 @@ function usage() {
 	exit
 }
 
+theos=""
+needdep=0
+findos
 myhome=$HOME
 update=0
 prog=$0
 installer=""
 CREATEREPO=0
+INSTALL=""
+DINSTALL=""
+DDEVEL=""
+DEVEL=""
 TZ='America/Chicago'
 while [[ $# -gt 0 ]]
 do
@@ -205,22 +300,15 @@ fi
 # Get the RHEL/CentOS Version
 ###
 
-if [ -f /etc/os-release ]
-then
-	. /etc/os-release
-else
-	if [ -f /etc/centos-release ]
-	then
-		VERSION_ID=`awk '{print $3}' /etc/centos-release | awk -F. '{print $1}'`
-		export VERSION_ID
-	elif [ -f /etc/redhat-release ]
-	then
-		VERSION_ID=`awk '{print $7}' /etc/redhat-release | awk -F. '{print $1}'`
-		export VERSION_ID
-	fi
-fi
 DNAME=`hostname -d`
-RPMLIST=`rpm -qa`
+RPMLIST=''
+if [ Z"$theos" = Z"centos" ] || [ Z"$theos" = Z"redhat" ] || [ Z"$theos" = Z"fedora" ]
+then
+	RPMLIST=`rpm -qa`
+elif [ Z"$theos" = Z"debian" ] || [ Z"$theos" = Z"ubuntu" ]
+then
+	RPMLIST=`dpkg -l`
+fi
 
 ###
 # Now do the base install
